### Python list vs numpy Arrays
Task:
1. Create a list of numbers from 1 to 20.
2. Task A: Use a list comprehension (Normal Python) to square every number 
3. Task B: Convert that list to a NumPy array and square the whole array at once.
4. Task C: Use the NumPy array to filter and only show numbers greater than 50. (Hint: array[array > 50])

In [2]:
import numpy as np

numbers = list=(range(1,21))

squared_list = [n**2 for n in numbers]

numpy_array = np.array(numbers)
squared_array = numpy_array ** 2

filtered = squared_array[squared_array >50]
print(filtered)

[ 64  81 100 121 144 169 196 225 256 289 324 361 400]


### NumPy operations: Creation, Shape, and Reshaping


In [7]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

print(f"Array : {arr}")

print(f"Shape of array: {arr.shape}")

print(f"First Three: {arr[:3]}")

data = np.array([1,2,3,4,5,6,7,8])
matrix = data.reshape(2,4)

print("Original data: ", data)
print("Reshaped into 2x4 matrix:\n",matrix)

print("Each element squared:",data **2)
print("Each element squared(matrix)\n",matrix **2)

Array : [1 2 3 4 5 6 7 8]
Shape of array: (8,)
First Three: [1 2 3]
Original data:  [1 2 3 4 5 6 7 8]
Reshaped into 2x4 matrix:
 [[1 2 3 4]
 [5 6 7 8]]
Each element squared: [ 1  4  9 16 25 36 49 64]
Each element squared(matrix)
 [[ 1  4  9 16]
 [25 36 49 64]]


- Create a NumPy array with numbers from 1 to 12.
- Reshape that array into a 3x4 matrix (3 rows, 4 columns).
- Extract the second row of that matrix.
- Math: Multiply every element in the matrix by 2 and print the result.

In [23]:
import numpy as np

arr_1 = np.array(range(1,13)) #arr_1 = np.arange(1, 13)  # More idiomatic
print(f"Array:{arr_1}")

print(f"Shape of array:{arr_1.shape}")

Reshaped = arr_1.reshape(3,4)
print("Reshaped:\n", Reshaped)
print("Second row:\n", Reshaped[1,2])

print("Each element multiplied by 2:\n", Reshaped*2)


Array:[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape of array:(12,)
Reshaped:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Second row:
 7
Each element multiplied by 2:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
